// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rubai-card-deck/Home.tsx": () => import("../components/mockups/rubai-card-deck/Home.tsx"),
  "./components/mockups/rubai-mission-control/Home.tsx": () => import("../components/mockups/rubai-mission-control/Home.tsx"),
  "./components/mockups/rubai-ambient-thread/Home.tsx": () => import("../components/mockups/rubai-ambient-thread/Home.tsx")
};
